[edit lock_screen][add autologout]

diff --git a/scripts/system/usr/local/bin/lock_screen b/scripts/system/usr/local/bin/lock_screen
--- a/scripts/system/usr/local/bin/lock_screen
+++ b/scripts/system/usr/local/bin/lock_screen
@@ -1,13 +1,39 @@
 #!/usr/bin/env bash
 
-# Exits if a command fails
+# exits if a command fails
 set -e
 
-if passwd -S | grep NP
-then
-	# No password set, so ask user to set one
-	gnome-terminal.real -t "⁣" --geometry=40x10 --wait -- passwd
-	sleep 1
+# launch new terminal and prompt afk phrase
+gnome-terminal.real -t "" --geometry=10x10 --wait -- bash -c "echo 'Write afk phrase, max: 50 sym:'; read test; echo \$test > /tmp/phrase;"
+
+# read phrase from file
+message=""
+while read -r line; do
+	message="$line"
+	break
+done < /tmp/phrase
+
+# len of phrase
+len="${#message}"
+
+# exit when len > 10
+if [[ len -gt 50 ]]; then
+	exit 1
 fi
 
-i3lock -c000000
+# remove tmp file
+rm /tmp/phrase
+
+# get display resolution
+x=$(xrandr | fgrep '*' | cut -d ' ' -f 4 | cut -d 'x' -f 1)
+y=$(xrandr | fgrep '*' | cut -d ' ' -f 4 | cut -d 'x' -f 2)
+
+# set text position
+text_x=$(( x - x / 2 - len * 14 ))
+text_y=$(( y - 50 ))
+draw="text "$text_x","$text_y" '$message'"
+
+# convert image
+convert /usr/share/backgrounds/01/logo.png -resize "$x"x"$y"! -pointsize 50 -fill white -draw "$draw" /tmp/logo.png
+# lock
+i3lock -i /tmp/logo.png
